apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gfch
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-gfch@sha256:400a2f59752135f739f8e449a534ad85970b84a91f64f008b9f497e2f2cf7612
        name: my-nodejs
        resources: {}
status: {}
